### ISSUE TITLE
Exception thrown when registering device connection

### ISSUE THREAD

**Issue by GoogleCodeExporter** [N004Drake/android-casual#18]
```
When Heimdall registers the device on Mac, the following exception is thrown:

[VERBOSE]Heimdall Device detected!
[DEBUG]State Change Detected, The new state is: 1
[DEBUG]Device Connected
[DEBUG]@stateConnected
Exception in thread "Connection Status" Exception in thread "Updating GUI" 
java.lang.IllegalStateException: Not on FX application thread; currentThread = 
Updating GUI
    at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:210)
    at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:393)
    at javafx.scene.Scene.addToDirtyList(Scene.java:529)
    at javafx.scene.Node.addToSceneDirtyList(Node.java:417)
    at javafx.scene.Node.impl_markDirty(Node.java:408)
    at javafx.scene.shape.Shape.impl_markDirty(Shape.java:930)
    at javafx.scene.Node.impl_geomChanged(Node.java:3758)
    at javafx.scene.text.Text.impl_geomChanged(Text.java:772)
    at javafx.scene.text.Text.needsTextLayout(Text.java:202)
    at javafx.scene.text.Text.needsFullTextLayout(Text.java:197)
    at javafx.scene.text.Text.access$400(Text.java:96)
    at javafx.scene.text.Text$4.invalidated(Text.java:396)
    at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
    at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:143)
    at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
    at javafx.scene.text.Text.setText(Text.java:377)
    at com.sun.javafx.scene.control.skin.TextAreaSkin$19.invalidated(TextAreaSkin.java:628)
    at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:339)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1116)
    at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1120)
    at javafx.scene.control.TextInputControl$TextProperty.invalidate(TextInputControl.java:1060)
    at javafx.scene.control.TextInputControl$TextProperty.access$200(TextInputControl.java:1032)
    at javafx.scene.control.TextInputControl$1.invalidated(TextInputControl.java:130)
    at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:135)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    at javafx.scene.control.TextArea$TextAreaContent.insert(TextArea.java:202)
    at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:464)
    at javafx.scene.control.TextInputControl.insertText(TextInputControl.java:394)
    at javafx.scene.control.TextInputControl.appendText(TextInputControl.java:384)
    at com.casual_dev.jodin.JOdinController.setInformationScrollBorderText(JOdinController.java:704)
    at CASUAL.Statics$1.run(Statics.java:238)
    at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: Not on FX application thread; currentThread = 
Connection Status
    at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:210)
    at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:393)
    at javafx.scene.Scene.addToDirtyList(Scene.java:529)
    at javafx.scene.Node.addToSceneDirtyList(Node.java:417)
    at javafx.scene.Node.impl_markDirty(Node.java:408)
    at javafx.scene.shape.Shape.impl_markDirty(Shape.java:930)
    at javafx.scene.Node.impl_geomChanged(Node.java:3758)
    at javafx.scene.text.Text.impl_geomChanged(Text.java:772)
    at javafx.scene.text.Text.needsTextLayout(Text.java:202)
    at javafx.scene.text.Text.needsFullTextLayout(Text.java:197)
    at javafx.scene.text.Text.access$400(Text.java:96)
    at javafx.scene.text.Text$4.invalidated(Text.java:396)
    at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
    at javafx.beans.property.StringPropertyBase.access$000(StringPropertyBase.java:49)
    at javafx.beans.property.StringPropertyBase$Listener.invalidated(StringPropertyBase.java:229)
    at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:135)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    at javafx.beans.binding.StringBinding.invalidate(StringBinding.java:171)
    at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51)
    at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:339)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1116)
    at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1120)
    at javafx.scene.control.TextInputControl$TextProperty.invalidate(TextInputControl.java:1060)
    at javafx.scene.control.TextInputControl$TextProperty.access$200(TextInputControl.java:1032)
    at javafx.scene.control.TextInputControl$1.invalidated(TextInputControl.java:130)
    at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:135)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    at javafx.scene.control.TextField$TextFieldContent.insert(TextField.java:82)
    at javafx.scene.control.TextInputControl$TextProperty.doSet(TextInputControl.java:1129)
    at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1055)
    at javafx.scene.control.TextInputControl.setText(TextInputControl.java:279)
    at com.casual_dev.jodin.JOdinController.deviceConnected(JOdinController.java:750)
    at CASUAL.CASUALConnectionStatusMonitor.stateSwitcher(CASUALConnectionStatusMonitor.java:163)
    at CASUAL.CASUALConnectionStatusMonitor.doDeviceCheck(CASUALConnectionStatusMonitor.java:144)
    at CASUAL.CASUALConnectionStatusMonitor.access$200(CASUALConnectionStatusMonitor.java:26)
    at CASUAL.CASUALConnectionStatusMonitor$1.run(CASUALConnectionStatusMonitor.java:117)
    at java.lang.Thread.run(Thread.java:745)


```

Original issue reported on code.google.com by `felderca...@gmail.com` on 6 May 2014 at 6:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `jrlo...@gmail.com` on 6 May 2014 at 7:15
- Changed state: **New**
- Added labels: **OpSys-OSX**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.  This looks like a JavaFX problem.  The bad news is this 
is like a  1:100 chance which I can't reproduce.  The good news is this problem 
has an easy fix.  In the JOdinController.deviceConnected, we just need to use a 
Platform.runLater(Runnable); 

Sorry for the inconvience and thanks for reporting.  It may be a couple of days 
until I can get this fixed.
```

Original comment by `adamoutler@gmail.com` on 6 May 2014 at 8:49

**Comment by GoogleCodeExporter** [comment]
```
I'm also getting this issue on Ubuntu 14.04 with Oracle Java8 installed.
```

Original comment by `viroatal...@gmail.com` on 4 Jul 2014 at 12:10

**Comment by GoogleCodeExporter** [comment]
```
You aren't getting this issue.  There is no longer code on the lines specified. 
 You need to ensure you are running the latest version and then file a new 
report.   
```

Original comment by `adamoutler@gmail.com` on 4 Jul 2014 at 12:27

**Comment by GoogleCodeExporter** [comment]
Original comment by `adamoutler@gmail.com` on 4 Jul 2014 at 12:28
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
This same issue still happens in version 1066
```

Original comment by `cve...@gmail.com` on 28 Jul 2014 at 6:05

**Comment by GoogleCodeExporter** [comment]
```
You need to submit a new bug report.  There is no code on the lines in this bug 
report anymore.
```

Original comment by `adamoutler@gmail.com` on 28 Jul 2014 at 9:52
